name: auto-format

on: push

permissions:
    actions: write
    checks: write


jobs:

    format:
        name: Format Code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: black
              uses: lgeiger/black-action@v1.0.1
              with:
                  args: .

            - name: Check for modified files
              id: git-check
              run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

            - name: Push changes
              run:
                  git config --global user.name ${{ github.actor }} 
                  git config --global user.email <${{ github.actor }}@users.noreply.github.com>
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git commit -am "Automated changes"
                  git push
