name: Lint

on:
  push:
    branches:
      - tinchi/linting
  pull_request:
    branches:
      - tinchi/linting

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Python dependencies
      run: pip install black

    - name: Install JavaScript and CSS dependencies
      run: npm install

    - name: Lint Python
      run: black ./src

    - name: Lint JavaScript
      run: npm run lint:js

    - name: Lint CSS
      run: npm run lint:css
